# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_ACTION_muV <- function(S, k_min, k_max, alpha, lambda = 1, AA_iters = 50L, Opt_iters = 0L, thread_no = 0L) {
    .Call(`_ACTIONmv_run_ACTION_muV`, S, k_min, k_max, alpha, lambda, AA_iters, Opt_iters, thread_no)
}

